class info {
  static List birds=[
    'Abbotts Babbler',
    'Abbotts Booby',
    'Abyssinian Ground Hornbill',
    'African Crowned Crane',
    'African Emerald Cuckoo',
    'African Firefinch',
    'African Oyster Catcher',
    'African Pied Hornbill',
    'Albatross',
    'Alberts Towhee',
    'Alexandrine Parakeet',
    'Alpine Chough',
    'Altamira Yellowthroat',
    'American Avocet',
    'American Bittern',
    'American Coot',
    'American Flamingo',
    'American Goldfinch',
    'American Kestrel',
    'American Pipit',
    'American Redstart',
    'American Wigeon',
    'Amethyst Woodstar',
    'Andean Goose',
    'Andean Lapwing',
    'Andean Siskin',
    'Anhinga',
    'Anianiau',
    'Annas Hummingbird',
    'Antbird',
    'Antillean Euphonia',
    'Apapane',
    'Apostlebird',
    'Araripe Manakin',
    'Ashy Storm Petrel',
    'Ashy Thrushbird',
    'Asian Crested Ibis',
    'Asian Dollard Bird',
    'Auckland Shaq',
    'Austral Canastero',
    'Australasian Figbird',
    'Avadavat',
    'Azaras Spinetail',
    'Azure Breasted Pitta',
    'Azure Jay',
    'Azure Tanager',
    'Azure Tit',
    'Baikal Teal',
    'Bald Eagle',
    'Bald Ibis',
    'Bali Starling',
    'Baltimore Oriole',
    'Bananaquit',
    'Band Tailed Guan',
    'Banded Broadbill',
    'Banded Pita',
    'Banded Stilt',
    'Bar-Tailed Godwit',
    'Barn Owl',
    'Barn Swallow',
    'Barred Puffbird',
    'Barrows Goldeneye',
    'Bay-Breasted Warbler',
    'Bearded Barbet',
    'Bearded Bellbird',
    'Bearded Reedling',
    'Belted Kingfisher',
    'Bird Of Paradise',
    'Black & Yellow Broadbill',
    'Black Baza',
    'Black Cockato',
    'Black Francolin',
    'Black Skimmer',
    'Black Swan',
    'Black Tail Crake',
    'Black Throated Bushtit',
    'Black Throated Warbler',
    'Black Vented Shearwater',
    'Black Vulture',
    'Black-Capped Chickadee',
    'Black-Necked Grebe',
    'Black-Throated Sparrow',
    'Blackburniam Warbler',
    'Blonde Crested Woodpecker',
    'Blood Pheasant',
    'Blue Coau',
    'Blue Dacnis',
    'Blue Grouse',
    'Blue Heron',
    'Blue Malkoha',
    'Blue Throated Toucanet',
    'Bobolink',
    'Bornean Bristlehead',
    'Bornean Leafbird',
    'Bornean Pheasant',
    'Brandt Cormarant',
    'Brewers Blackbird',
    'Brown Crepper',
    'Brown Noody',
    'Brown Thrasher',
    'Bufflehead',
    'Bulwers Pheasant',
    'Burchells Courser',
    'Bush Turkey',
    'Caatinga Cacholote',
    'Cactus Wren',
    'California Condor',
    'California Gull',
    'California Quail',
    'Campo Flicker',
    'Canary',
    'Cape Glossy Starling',
    'Cape Longclaw',
    'Cape May Warbler',
    'Cape Rock Thrush',
    'Capped Heron',
    'Capuchinbird',
    'Carmine Bee-Eater',
    'Caspian Tern',
    'Cassowary',
    'Cedar Waxwing',
    'Cerulean Warbler',
    'Chara De Collar',
    'Chattering Lory',
    'Chestnet Bellied Euphonia',
    'Chinese Bamboo Partridge',
    'Chinese Pond Heron',
    'Chipping Sparrow',
    'Chucao Tapaculo',
    'Chukar Partridge',
    'Cinnamon Attila',
    'Cinnamon Flycatcher',
    'Cinnamon Teal',
    'Clarks Nutcracker',
    'Cock Of The  Rock',
    'Cockatoo',
    'Collared Aracari',
    'Common Firecrest',
    'Common Grackle',
    'Common House Martin',
    'Common Iora',
    'Common Loon',
    'Common Poorwill',
    'Common Starling',
    'Coppery Tailed Coucal',
    'Crab Plover',
    'Crane Hawk',
    'Cream Colored Woodpecker',
    'Crested Auklet',
    'Crested Caracara',
    'Crested Coua',
    'Crested Fireback',
    'Crested Kingfisher',
    'Crested Nuthatch',
    'Crested Oropendola',
    'Crested Shriketit',
    'Crimson Chat',
    'Crimson Sunbird',
    'Crow',
    'Crowned Pigeon',
    'Cuban Tody',
    'Cuban Trogon',
    'Curl Crested Aracuri',
    'D-Arnauds Barbet',
    'Dalmatian Pelican',
    'Darjeeling Woodpecker',
    'Dark Eyed Junco',
    'Darwins Flycatcher',
    'Daurian Redstart',
    'Demoiselle Crane',
    'Double Barred Finch',
    'Double Brested Cormarant',
    'Double Eyed Fig Parrot',
    'Downy Woodpecker',
    'Dusky Lory',
    'Dusky Robin',
    'Eared Pita',
    'Eastern Bluebird',
    'Eastern Bluebonnet',
    'Eastern Golden Weaver',
    'Eastern Meadowlark',
    'Eastern Rosella',
    'Eastern Towee',
    'Eastern Wip Poor Will',
    'Ecuadorian Hillstar',
    'Egyptian Goose',
    'Elegant Trogon',
    'Elliots  Pheasant',
    'Emerald Tanager',
    'Emperor Penguin',
    'Emu',
    'Enggano Myna',
    'Eurasian Bullfinch',
    'Eurasian Golden Oriole',
    'Eurasian Magpie',
    'European Goldfinch',
    'European Turtle Dove',
    'Evening Grosbeak',
    'Fairy Bluebird',
    'Fairy Penguin',
    'Fairy Tern',
    'Fan Tailed Widow',
    'Fasciated Wren',
    'Fiery Minivet',
    'Fiordland Penguin',
    'Fire Tailled Myzornis',
    'Flame Bowerbird',
    'Flame Tanager',
    'Frigate',
    'Gambels Quail',
    'Gang Gang Cockatoo',
    'Gila Woodpecker',
    'Gilded Flicker',
    'Glossy Ibis',
    'Go Away Bird',
    'Gold Wing Warbler',
    'Golden Bower Bird',
    'Golden Cheeked Warbler',
    'Golden Chlorophonia',
    'Golden Eagle',
    'Golden Parakeet',
    'Golden Pheasant',
    'Golden Pipit',
    'Gouldian Finch',
    'Grandala',
    'Gray Catbird',
    'Gray Kingbird',
    'Gray Partridge',
    'Great Gray Owl',
    'Great Jacamar',
    'Great Kiskadee',
    'Great Potoo',
    'Great Tinamou',
    'Great Xenops',
    'Greater Pewee',
    'Greator Sage Grouse',
    'Green Broadbill',
    'Green Jay',
    'Green Magpie',
    'Grey Cuckooshrike',
    'Grey Plover',
    'Groved Billed Ani',
    'Guinea Turaco',
    'Guineafowl',
    'Gurneys Pitta',
    'Gyrfalcon',
    'Hamerkop',
    'Harlequin Duck',
    'Harlequin Quail',
    'Harpy Eagle',
    'Hawaiian Goose',
    'Hawfinch',
    'Helmet Vanga',
    'Hepatic Tanager',
    'Himalayan Bluetail',
    'Himalayan Monal',
    'Hoatzin',
    'Hooded Merganser',
    'Hoopoes',
    'Horned Guan',
    'Horned Lark',
    'Horned Sungem',
    'House Finch',
    'House Sparrow',
    'Hyacinth Macaw',
    'Iberian Magpie',
    'Ibisbill',
    'Imperial Shaq',
    'Inca Tern',
    'Indian Bustard',
    'Indian Pitta',
    'Indian Roller',
    'Indian Vulture',
    'Indigo Bunting',
    'Indigo Flycatcher',
    'Inland Dotterel',
    'Ivory Billed Aracari',
    'Ivory Gull',
    'Iwi',
    'Jabiru',
    'Jack Snipe',
    'Jandaya Parakeet',
    'Japanese Robin',
    'Java Sparrow',
    'Jocotoco Antpitta',
    'Kagu',
    'Kakapo',
    'Killdear',
    'King Eider',
    'King Vulture',
    'Kiwi',
    'Kookaburra',
    'Lark Bunting',
    'Lazuli Bunting',
    'Lesser Adjutant',
    'Lilac Roller',
    'Little Auk',
    'Loggerhead Shrike',
    'Long-Eared Owl',
    'Magpie Goose',
    'Malabar Hornbill',
    'Malachite Kingfisher',
    'Malagasy White Eye',
    'Maleo',
    'Mallard Duck',
    'Mandrin Duck',
    'Mangrove Cuckoo',
    'Marabou Stork',
    'Masked Booby',
    'Masked Lapwing',
    'Mckays Bunting',
    'Mikado  Pheasant',
    'Mourning Dove',
    'Myna',
    'Nicobar Pigeon',
    'Noisy Friarbird',
    'Northern Beardless Tyrannulet',
    'Northern Cardinal',
    'Northern Flicker',
    'Northern Fulmar',
    'Northern Gannet',
    'Northern Goshawk',
    'Northern Jacana',
    'Northern Mockingbird',
    'Northern Parula',
    'Northern Red Bishop',
    'Northern Shoveler',
    'Ocellated Turkey',
    'Okinawa Rail',
    'Orange Brested Bunting',
    'Oriental Bay Owl',
    'Osprey',
    'Ostrich',
    'Ovenbird',
    'Oyster Catcher',
    'Painted Bunting',
    'Palila',
    'Paradise Tanager',
    'Parakett  Akulet',
    'Parus Major',
    'Patagonian Sierra Finch',
    'Peacock',
    'Peregrine Falcon',
    'Philippine Eagle',
    'Pink Robin',
    'Pomarine Jaeger',
    'Puffin',
    'Purple Finch',
    'Purple Gallinule',
    'Purple Martin',
    'Purple Swamphen',
    'Pygmy Kingfisher',
    'Quetzal',
    'Rainbow Lorikeet',
    'Razorbill',
    'Red Bearded Bee Eater',
    'Red Bellied Pitta',
    'Red Browed Finch',
    'Red Faced Cormorant',
    'Red Faced Warbler',
    'Red Fody',
    'Red Headed Duck',
    'Red Headed Woodpecker',
    'Red Honey Creeper',
    'Red Naped Trogon',
    'Red Tailed Hawk',
    'Red Tailed Thrush',
    'Red Winged Blackbird',
    'Red Wiskered Bulbul',
    'Regent Bowerbird',
    'Ring-Necked Pheasant',
    'Roadrunner',
    'Robin',
    'Rock Dove',
    'Rosy Faced Lovebird',
    'Rough Leg Buzzard',
    'Royal Flycatcher',
    'Ruby Throated Hummingbird',
    'Rudy Kingfisher',
    'Rufous Kingfisher',
    'Rufuos Motmot',
    'Samatran Thrush',
    'Sand Martin',
    'Sandhill Crane',
    'Satyr Tragopan',
    'Scarlet Crowned Fruit Dove',
    'Scarlet Ibis',
    'Scarlet Macaw',
    'Scarlet Tanager',
    'Shoebill',
    'Short Billed Dowitcher',
    'Skua',
    'Smiths Longspur',
    'Snowy Egret',
    'Snowy Owl',
    'Snowy Plover',
    'Sora',
    'Spangled Cotinga',
    'Splendid Wren',
    'Spoon Biled Sandpiper',
    'Spoonbill',
    'Spotted Catbird',
    'Sri Lanka Blue Magpie',
    'Steamer Duck',
    'Stork Billed Kingfisher',
    'Strawberry Finch',
    'Striped Owl',
    'Stripped Manakin',
    'Stripped Swallow',
    'Superb Starling',
    'Swinhoes Pheasant',
    'Tailorbird',
    'Taiwan Magpie',
    'Takahe',
    'Tasmanian Hen',
    'Teal Duck',
    'Tit Mouse',
    'Touchan',
    'Townsends Warbler',
    'Tree Swallow',
    'Tricolored Blackbird',
    'Tropical Kingbird',
    'Trumpter Swan',
    'Turkey Vulture',
    'Turquoise Motmot',
    'Umbrella Bird',
    'Varied Thrush',
    'Veery',
    'Venezuelian Troupial',
    'Vermilion Flycather',
    'Victoria Crowned Pigeon',
    'Violet Green Swallow',
    'Violet Turaco',
    'Vulturine Guineafowl',
    'Wall Creaper',
    'Wattled Curassow',
    'Wattled Lapwing',
    'Whimbrel',
    'White Browed Crake',
    'White Cheeked Turaco',
    'White Crested Hornbill',
    'White Necked Raven',
    'White Tailed Tropic',
    'White Throated Bee Eater',
    'Wild Turkey',
    'Wilsons Bird Of Paradise',
    'Wood Duck',
    'Yellow Bellied Flowerpecker',
    'Yellow Cacique',
    'Yellow Headed Blackbird',
  ];
  static Map<String,String> weblink={
    'Abbotts Babbler':'https://en.m.wikipedia.org/wiki/Abbott%27s_babbler',
    'Abbotts Booby':'https://en.m.wikipedia.org/wiki/Abbott%27s_booby',
    'Abyssinian Ground Hornbill':'https://en.m.wikipedia.org/wiki/Abyssinian_ground_hornbill',
    'African Crowned Crane':'https://en.m.wikipedia.org/wiki/Grey_crowned_crane',
    'African Emerald Cuckoo':'https://en.m.wikipedia.org/wiki/African_emerald_cuckoo',
    'African Firefinch':'https://en.m.wikipedia.org/wiki/African_firefinch',
    'African Oyster Catcher': 'https://en.m.wikipedia.org/wiki/African_oystercatcher',
    'African Pied Hornbill': 'https://en.m.wikipedia.org/wiki/African_pied_hornbill',
    'Albatross': 'https://en.m.wikipedia.org/wiki/Albatross',
    'Alberts Towhee': 'https://en.m.wikipedia.org/wiki/Abert%27s_towhee',
    'Alexandrine Parakeet': 'https://en.m.wikipedia.org/wiki/Alexandrine_parakeet',
    'Alpine Chough': 'https://en.m.wikipedia.org/wiki/Alpine_chough',
    'Altamira Yellowthroat': 'https://en.m.wikipedia.org/wiki/Altamira_yellowthroat',
    'American Avocet': 'https://en.m.wikipedia.org/wiki/American_avocet',
    'American Bittern': 'https://en.m.wikipedia.org/wiki/American_bittern',
    'American Coot': 'https://en.m.wikipedia.org/wiki/American_coot',
    'American Flamingo': 'https://en.m.wikipedia.org/wiki/American_flamingo',
    'American Goldfinch': 'https://en.m.wikipedia.org/wiki/American_goldfinch',
    'American Kestrel': 'https://en.m.wikipedia.org/wiki/American_kestrel',
    'American Pipit': 'https://en.m.wikipedia.org/wiki/Buff-bellied_pipit',
    'American Redstart': 'https://en.m.wikipedia.org/wiki/American_redstart',
    'American Wigeon': 'https://en.m.wikipedia.org/wiki/American_wigeon',
    'Amethyst Woodstar': 'https://en.m.wikipedia.org/wiki/Amethyst_woodstar',
    'Andean Goose': 'https://en.m.wikipedia.org/wiki/Andean_goose',
    'Andean Lapwing': 'https://en.m.wikipedia.org/wiki/Andean_lapwing',
    'Andean Siskin': 'https://en.m.wikipedia.org/wiki/Andean_siskin',
    'Anhinga': 'https://en.m.wikipedia.org/wiki/Anhinga',
    'Anianiau': 'https://en.m.wikipedia.org/wiki/%CA%BBAnianiau',
    'Annas Hummingbird': 'https://en.m.wikipedia.org/wiki/Anna%27s_hummingbird',
    'Antbird': 'https://en.m.wikipedia.org/wiki/Antbird',
    'Antillean Euphonia': 'https://en.m.wikipedia.org/wiki/Antillean_euphonia',
    'Apapane': 'https://en.m.wikipedia.org/wiki/%CA%BBApapane',
    'Apostlebird': 'https://en.m.wikipedia.org/wiki/Apostlebird',
    'Araripe Manakin': 'https://en.m.wikipedia.org/wiki/Araripe_manakin',
    'Ashy Storm Petrel': 'https://en.m.wikipedia.org/wiki/Ashy_storm_petrel',
    'Ashy Thrushbird': 'https://en.m.wikipedia.org/wiki/Ashy_thrush',
    'Asian Crested Ibis': 'https://en.m.wikipedia.org/wiki/Crested_ibis',
    'Asian Dollard Bird': 'https://en.m.wikipedia.org/wiki/Oriental_dollarbird',
    'Auckland Shaq': 'https://en.m.wikipedia.org/wiki/Auckland_shag',
    'Austral Canastero': 'https://en.m.wikipedia.org/wiki/Austral_canastero',
    'Australasian Figbird': 'https://en.m.wikipedia.org/wiki/Australasian_figbird',
    'Avadavat': 'https://en.m.wikipedia.org/wiki/Amandava',
    'Azaras Spinetail': 'https://en.m.wikipedia.org/wiki/Azara%27s_spinetail',
    'Azure Breasted Pitta': 'https://en.m.wikipedia.org/wiki/Azure-breasted_pitta',
    'Azure Jay': 'https://en.m.wikipedia.org/wiki/Azure_jay',
    'Azure Tanager': 'https://en.m.wikipedia.org/wiki/Azure-shouldered_tanager',
    'Azure Tit': 'https://en.m.wikipedia.org/wiki/Azure_tit',
    'Baikal Teal': 'https://en.m.wikipedia.org/wiki/Baikal_teal',
    'Bald Eagle': 'https://en.m.wikipedia.org/wiki/Bald_eagle',
    'Bald Ibis': 'https://en.m.wikipedia.org/wiki/Geronticus',
    'Bali Starling': 'https://en.m.wikipedia.org/wiki/Bali_myna',
    'Baltimore Oriole': 'https://en.m.wikipedia.org/wiki/Baltimore_oriole',
    'Bananaquit': 'https://en.m.wikipedia.org/wiki/Bananaquit',
    'Band Tailed Guan': 'https://en.m.wikipedia.org/wiki/Band-tailed_guan',
    'Banded Broadbill': 'https://en.m.wikipedia.org/wiki/Banded_broadbill',
    'Banded Pita': 'https://en.m.wikipedia.org/wiki/Banded_pitta',
    'Banded Stilt': 'https://en.m.wikipedia.org/wiki/Banded_stilt',
    'Bar-Tailed Godwit': 'https://en.m.wikipedia.org/wiki/Bar-tailed_godwit',
    'Barn Owl': 'https://en.m.wikipedia.org/wiki/Barn_owl',
    'Barn Swallow': 'https://en.m.wikipedia.org/wiki/Barn_swallow',
    'Barred Puffbird': 'https://en.m.wikipedia.org/wiki/Barred_puffbird',
    'Barrows Goldeneye': 'https://en.m.wikipedia.org/wiki/Barrow%27s_goldeneye',
    'Bay-Breasted Warbler': 'https://en.m.wikipedia.org/wiki/Bay-breasted_warbler',
    'Bearded Barbet': 'https://en.m.wikipedia.org/wiki/Bearded_barbet',
    'Bearded Bellbird': 'https://en.m.wikipedia.org/wiki/Bearded_bellbird',
    'Bearded Reedling': 'https://en.m.wikipedia.org/wiki/Bearded_reedling',
    'Belted Kingfisher': 'https://en.m.wikipedia.org/wiki/Belted_kingfisher',
    'Bird Of Paradise': 'https://en.m.wikipedia.org/wiki/Bird-of-paradise',
    'Black & Yellow Broadbill': 'https://en.m.wikipedia.org/wiki/Black-and-yellow_broadbill',
    'Black Baza': 'https://en.m.wikipedia.org/wiki/Black_baza',
    'Black Cockato': 'https://en.m.wikipedia.org/wiki/Carnaby%27s_black_cockatoo',
    'Black Francolin': 'https://en.m.wikipedia.org/wiki/Black_francolin',
    'Black Skimmer': 'https://en.m.wikipedia.org/wiki/Black_skimmer',
    'Black Swan': 'https://en.m.wikipedia.org/wiki/Black_swan',
    'Black Tail Crake': 'https://en.m.wikipedia.org/wiki/Black-tailed_crake',
    'Black Throated Bushtit': 'https://en.m.wikipedia.org/wiki/Black-throated_bushtit',
    'Black Throated Warbler': 'https://en.m.wikipedia.org/wiki/Black-throated_blue_warbler',
    'Black Vented Shearwater': 'https://en.m.wikipedia.org/wiki/Black-vented_shearwater',
    'Black Vulture': 'https://en.m.wikipedia.org/wiki/Black_vulture',
    'Black-Capped Chickadee': 'https://en.m.wikipedia.org/wiki/Black-capped_chickadee',
    'Black-Necked Grebe': 'https://en.m.wikipedia.org/wiki/Black-necked_grebe',
    'Black-Throated Sparrow': 'https://en.m.wikipedia.org/wiki/Black-throated_sparrow',
    'Blackburniam Warbler': 'https://en.m.wikipedia.org/wiki/Blackburnian_warbler',
    'Blonde Crested Woodpecker': 'https://en.m.wikipedia.org/wiki/Blond-crested_woodpecker',
    'Blood Pheasant': 'https://en.m.wikipedia.org/wiki/Blood_pheasant',
    'Blue Coau': 'https://en.m.wikipedia.org/wiki/Blue_coua',
    'Blue Dacnis': 'https://en.m.wikipedia.org/wiki/Blue_dacnis',
    'Blue Grouse': 'https://en.m.wikipedia.org/wiki/Dendragapus',
    'Blue Heron': 'https://en.m.wikipedia.org/wiki/Great_blue_heron',
    'Blue Malkoha': 'https://en.m.wikipedia.org/wiki/Blue_malkoha',
    'Blue Throated Toucanet': 'https://en.m.wikipedia.org/wiki/Blue-throated_toucanet',
    'Bobolink': 'https://en.m.wikipedia.org/wiki/Bobolink',
    'Bornean Bristlehead': 'https://en.m.wikipedia.org/wiki/Bornean_bristlehead',
    'Bornean Leafbird': 'https://en.m.wikipedia.org/wiki/Bornean_leafbird',
    'Bornean Pheasant': 'https://en.m.wikipedia.org/wiki/Bornean_peacock-pheasant',
    'Brandt Cormarant': 'https://en.m.wikipedia.org/wiki/Brandt%27s_cormorant',
    'Brewers Blackbird': 'https://en.m.wikipedia.org/wiki/Brewer%27s_blackbird',
    'Brown Crepper': 'https://en.m.wikipedia.org/wiki/Brown_creeper',
    'Brown Noody': 'https://en.m.wikipedia.org/wiki/Brown_noddy',
    'Brown Thrasher': 'https://en.m.wikipedia.org/wiki/Brown_thrasher',
    'Bufflehead': 'https://en.m.wikipedia.org/wiki/Bufflehead',
    'Bulwers Pheasant': 'https://en.m.wikipedia.org/wiki/Bulwer%27s_pheasant',
    'Burchells Courser': 'https://en.m.wikipedia.org/wiki/Burchell%27s_courser',
    'Bush Turkey': 'https://en.m.wikipedia.org/wiki/Australian_brushturkey',
    'Caatinga Cacholote': 'https://en.m.wikipedia.org/wiki/Caatinga_cacholote',
    'Cactus Wren': 'https://en.m.wikipedia.org/wiki/Cactus_wren',
    'California Condor': 'https://en.m.wikipedia.org/wiki/California_condor',
    'California Gull': 'https://en.m.wikipedia.org/wiki/California_gull',
    'California Quail': 'https://en.m.wikipedia.org/wiki/California_quail',
    'Campo Flicker': 'https://en.m.wikipedia.org/wiki/Campo_flicker',
    'Canary': 'https://en.m.wikipedia.org/wiki/Atlantic_canary',
    'Cape Glossy Starling': 'https://en.m.wikipedia.org/wiki/Cape_starling',
    'Cape Longclaw': 'https://en.m.wikipedia.org/wiki/Cape_longclaw',
    'Cape May Warbler': 'https://en.m.wikipedia.org/wiki/Cape_May_warbler',
    'Cape Rock Thrush': 'https://en.m.wikipedia.org/wiki/Cape_rock_thrush',
    'Capped Heron': 'https://en.m.wikipedia.org/wiki/Capped_heron',
    'Capuchinbird': 'https://en.m.wikipedia.org/wiki/Capuchinbird',
    'Carmine Bee-Eater': 'https://en.m.wikipedia.org/wiki/Northern_carmine_bee-eater',
    'Caspian Tern': 'https://en.m.wikipedia.org/wiki/Caspian_tern',
    'Cassowary': 'https://en.m.wikipedia.org/wiki/Cassowary',
    'Cedar Waxwing': 'https://en.m.wikipedia.org/wiki/Cedar_waxwing',
    'Cerulean Warbler': 'https://en.m.wikipedia.org/wiki/Cerulean_warbler',
    'Chara De Collar': 'https://en.m.wikipedia.org/wiki/Woodhouse%27s_scrub_jay',
    'Chattering Lory': 'https://en.m.wikipedia.org/wiki/Chattering_lory',
    'Chestnet Bellied Euphonia': 'https://en.m.wikipedia.org/wiki/Chestnut-bellied_euphonia',
    'Chinese Bamboo Partridge': 'https://en.m.wikipedia.org/wiki/Chinese_bamboo_partridge',
    'Chinese Pond Heron': 'https://en.m.wikipedia.org/wiki/Chinese_pond_heron',
    'Chipping Sparrow': 'https://en.m.wikipedia.org/wiki/Chipping_sparrow',
    'Chucao Tapaculo': 'https://en.m.wikipedia.org/wiki/Chucao_tapaculo',
    'Chukar Partridge': 'https://en.m.wikipedia.org/wiki/Chukar_partridge',
    'Cinnamon Attila': 'https://en.m.wikipedia.org/wiki/Cinnamon_attila',
    'Cinnamon Flycatcher': 'https://en.m.wikipedia.org/wiki/Cinnamon_flycatcher',
    'Cinnamon Teal': 'https://en.m.wikipedia.org/wiki/Cinnamon_teal',
    'Clarks Nutcracker': 'https://en.m.wikipedia.org/wiki/Clark%27s_nutcracker',
    'Cock Of The  Rock': 'https://en.m.wikipedia.org/wiki/Cock-of-the-rock',
    'Cockatoo': 'https://en.m.wikipedia.org/wiki/Cockatoo',
    'Collared Aracari': 'https://en.m.wikipedia.org/wiki/Collared_aracari',
    'Common Firecrest': 'https://en.m.wikipedia.org/wiki/Common_firecrest',
    'Common Grackle': 'https://en.m.wikipedia.org/wiki/Common_grackle',
    'Common House Martin': 'https://en.m.wikipedia.org/wiki/Common_house_martin',
    'Common Iora': 'https://en.m.wikipedia.org/wiki/Common_iora',
    'Common Loon': 'https://en.m.wikipedia.org/wiki/Common_loon',
    'Common Poorwill': 'https://en.m.wikipedia.org/wiki/Common_poorwill',
    'Common Starling': 'https://en.m.wikipedia.org/wiki/Common_starling',
    'Coppery Tailed Coucal': 'https://en.m.wikipedia.org/wiki/Coppery-tailed_coucal',
    'Crab Plover': 'https://en.m.wikipedia.org/wiki/Crab-plover',
    'Crane Hawk': 'https://en.m.wikipedia.org/wiki/Crane_hawk',
    'Cream Colored Woodpecker': 'https://en.m.wikipedia.org/wiki/Cream-colored_woodpecker',
    'Crested Auklet': 'https://en.m.wikipedia.org/wiki/Crested_auklet',
    'Crested Caracara': 'https://en.m.wikipedia.org/wiki/Crested_caracara',
    'Crested Coua': 'https://en.m.wikipedia.org/wiki/Crested_coua',
    'Crested Fireback': 'https://en.m.wikipedia.org/wiki/Crested_fireback',
    'Crested Kingfisher': 'https://en.m.wikipedia.org/wiki/Crested_kingfisher',
    'Crested Nuthatch': 'https://en.m.wikipedia.org/wiki/Red-breasted_nuthatch',
    'Crested Oropendola': 'https://en.m.wikipedia.org/wiki/Crested_oropendola',
    'Crested Shriketit': 'https://en.m.wikipedia.org/wiki/Crested_shriketit',
    'Crimson Chat': 'https://en.m.wikipedia.org/wiki/Crimson_chat',
    'Crimson Sunbird': 'https://en.m.wikipedia.org/wiki/Crimson_sunbird',
    'Crow': 'https://en.m.wikipedia.org/wiki/Crow',
    'Crowned Pigeon': 'https://en.m.wikipedia.org/wiki/Crowned_pigeon',
    'Cuban Tody': 'https://en.m.wikipedia.org/wiki/Cuban_tody',
    'Cuban Trogon': 'https://en.m.wikipedia.org/wiki/Cuban_trogon',
    'Curl Crested Aracuri': 'https://en.m.wikipedia.org/wiki/Curl-crested_aracari',
    'D-Arnauds Barbet': 'https://en.m.wikipedia.org/wiki/D%27Arnaud%27s_barbet',
    'Dalmatian Pelican': 'https://en.m.wikipedia.org/wiki/Dalmatian_pelican',
    'Darjeeling Woodpecker': 'https://en.m.wikipedia.org/wiki/Darjeeling_woodpecker',
    'Dark Eyed Junco': 'https://en.m.wikipedia.org/wiki/Dark-eyed_junco',
    'Darwins Flycatcher': 'https://en.m.wikipedia.org/wiki/Darwin%27s_flycatcher',
    'Daurian Redstart': 'https://en.m.wikipedia.org/wiki/Daurian_redstart',
    'Demoiselle Crane': 'https://en.m.wikipedia.org/wiki/Demoiselle_crane',
    'Double Barred Finch': 'https://en.m.wikipedia.org/wiki/Double-barred_finch',
    'Double Brested Cormarant': 'https://en.m.wikipedia.org/wiki/Double-crested_cormorant',
    'Double Eyed Fig Parrot': 'https://en.m.wikipedia.org/wiki/Double-eyed_fig_parrot',
    'Downy Woodpecker': 'https://en.m.wikipedia.org/wiki/Downy_woodpecker',
    'Dusky Lory': 'https://en.m.wikipedia.org/wiki/Dusky_lory',
    'Dusky Robin': 'https://en.m.wikipedia.org/wiki/Dusky_robin',
    'Eared Pita': 'https://en.m.wikipedia.org/wiki/Eared_pitta',
    'Eastern Bluebird': 'https://en.m.wikipedia.org/wiki/Eastern_bluebird',
    'Eastern Bluebonnet': 'https://en.m.wikipedia.org/wiki/Eastern_bluebonnet',
    'Eastern Golden Weaver': 'https://en.m.wikipedia.org/wiki/Eastern_golden_weaver',
    'Eastern Meadowlark': 'https://en.m.wikipedia.org/wiki/Eastern_meadowlark',
    'Eastern Rosella': 'https://en.m.wikipedia.org/wiki/Eastern_rosella',
    'Eastern Towee': 'https://en.m.wikipedia.org/wiki/Eastern_towhee',
    'Eastern Wip Poor Will': 'https://en.m.wikipedia.org/wiki/Eastern_whip-poor-will',
    'Ecuadorian Hillstar': 'https://en.m.wikipedia.org/wiki/Ecuadorian_hillstar',
    'Egyptian Goose': 'https://en.m.wikipedia.org/wiki/Egyptian_goose',
    'Elegant Trogon': 'https://en.m.wikipedia.org/wiki/Elegant_trogon',
    'Elliots  Pheasant': 'https://en.m.wikipedia.org/wiki/Elliot%27s_pheasant',
    'Emerald Tanager': 'https://en.m.wikipedia.org/wiki/Emerald_tanager',
    'Emperor Penguin': 'https://en.m.wikipedia.org/wiki/Emperor_penguin',
    'Emu': 'https://en.m.wikipedia.org/wiki/Emu',
    'Enggano Myna': 'https://en.m.wikipedia.org/wiki/Common_hill_myna',
    'Eurasian Bullfinch': 'https://en.m.wikipedia.org/wiki/Eurasian_bullfinch',
    'Eurasian Golden Oriole': 'https://en.m.wikipedia.org/wiki/Eurasian_golden_oriole',
    'Eurasian Magpie': 'https://en.m.wikipedia.org/wiki/Eurasian_magpie',
    'European Goldfinch': 'https://en.m.wikipedia.org/wiki/European_goldfinch',
    'European Turtle Dove': 'https://en.m.wikipedia.org/wiki/European_turtle_dove',
    'Evening Grosbeak': 'https://en.m.wikipedia.org/wiki/Evening_grosbeak',
    'Fairy Bluebird': 'https://en.m.wikipedia.org/wiki/Fairy-bluebird',
    'Fairy Penguin': 'https://en.m.wikipedia.org/wiki/Eudyptula_novaehollandiae',
    'Fairy Tern': 'https://en.m.wikipedia.org/wiki/Fairy_tern',
    'Fan Tailed Widow': 'https://en.m.wikipedia.org/wiki/Fan-tailed_widowbird',
    'Fasciated Wren': 'https://en.m.wikipedia.org/wiki/Fasciated_wren',
    'Fiery Minivet': 'https://en.m.wikipedia.org/wiki/Fiery_minivet',
    'Fiordland Penguin': 'https://en.m.wikipedia.org/wiki/Fiordland_penguin',
    'Fire Tailled Myzornis': 'https://en.m.wikipedia.org/wiki/Fire-tailed_myzornis',
    'Flame Bowerbird': 'https://en.m.wikipedia.org/wiki/Flame_bowerbird',
    'Flame Tanager': 'https://en.m.wikipedia.org/wiki/Flame-colored_tanager',
    'Frigate': 'https://en.m.wikipedia.org/wiki/Frigatebird',
    'Gambels Quail': 'https://en.m.wikipedia.org/wiki/Gambel%27s_quail',
    'Gang Gang Cockatoo': 'https://en.m.wikipedia.org/wiki/Gang-gang_cockatoo',
    'Gila Woodpecker': 'https://en.m.wikipedia.org/wiki/Gila_woodpecker',
    'Gilded Flicker': 'https://en.m.wikipedia.org/wiki/Gilded_flicker',
    'Glossy Ibis': 'https://en.m.wikipedia.org/wiki/Glossy_ibis',
    'Go Away Bird': 'https://en.m.wikipedia.org/wiki/Crinifer',
    'Gold Wing Warbler': 'https://en.m.wikipedia.org/wiki/Golden-winged_warbler',
    'Golden Bower Bird': 'https://en.m.wikipedia.org/wiki/Golden_bowerbird',
    'Golden Cheeked Warbler': 'https://en.m.wikipedia.org/wiki/Golden-cheeked_warbler',
    'Golden Chlorophonia': 'https://en.m.wikipedia.org/wiki/Golden-browed_chlorophonia',
    'Golden Eagle': 'https://en.m.wikipedia.org/wiki/Golden_eagle',
    'Golden Parakeet': 'https://en.m.wikipedia.org/wiki/Golden_parakeet',
    'Golden Pheasant': 'https://en.m.wikipedia.org/wiki/Golden_pheasant',
    'Golden Pipit': 'https://en.m.wikipedia.org/wiki/Golden_pipit',
    'Gouldian Finch': 'https://en.m.wikipedia.org/wiki/Gouldian_finch',
    'Grandala': 'https://en.m.wikipedia.org/wiki/Grandala',
    'Gray Catbird': 'https://en.m.wikipedia.org/wiki/Gray_catbird',
    'Gray Kingbird': 'https://en.m.wikipedia.org/wiki/Gray_kingbird',
    'Gray Partridge': 'https://en.m.wikipedia.org/wiki/Grey_partridge',
    'Great Gray Owl': 'https://en.m.wikipedia.org/wiki/Great_grey_owl',
    'Great Jacamar': 'https://en.m.wikipedia.org/wiki/Great_jacamar',
    'Great Kiskadee': 'https://en.m.wikipedia.org/wiki/Great_kiskadee',
    'Great Potoo': 'https://en.m.wikipedia.org/wiki/Great_potoo',
    'Great Tinamou': 'https://en.m.wikipedia.org/wiki/Great_tinamou',
    'Great Xenops': 'https://en.m.wikipedia.org/wiki/Great_xenops',
    'Greater Pewee': 'https://en.m.wikipedia.org/wiki/Greater_pewee',
    'Greator Sage Grouse': 'https://en.m.wikipedia.org/wiki/Greater_sage-grouse',
    'Green Broadbill': 'https://en.m.wikipedia.org/wiki/Green_broadbill',
    'Green Jay': 'https://en.m.wikipedia.org/wiki/Green_jay',
    'Green Magpie': 'https://en.m.wikipedia.org/wiki/Cissa_(genus)',
    'Grey Cuckooshrike': 'https://en.m.wikipedia.org/wiki/Grey_cuckooshrike',
    'Grey Plover': 'https://en.m.wikipedia.org/wiki/Grey_plover',
    'Groved Billed Ani': 'https://en.m.wikipedia.org/wiki/Groove-billed_ani',
    'Guinea Turaco': 'https://en.m.wikipedia.org/wiki/Guinea_turaco',
    'Guineafowl': 'https://en.m.wikipedia.org/wiki/Guineafowl',
    'Gurneys Pitta': 'https://en.m.wikipedia.org/wiki/Gurney%27s_pitta',
    'Gyrfalcon': 'https://en.m.wikipedia.org/wiki/Gyrfalcon',
    'Hamerkop': 'https://en.m.wikipedia.org/wiki/Hamerkop',
    'Harlequin Duck': 'https://en.m.wikipedia.org/wiki/Harlequin_duck',
    'Harlequin Quail': 'https://en.m.wikipedia.org/wiki/Harlequin_quail',
    'Harpy Eagle': 'https://en.m.wikipedia.org/wiki/Harpy_eagle',
    'Hawaiian Goose': 'https://en.m.wikipedia.org/wiki/Nene_(bird)',
    'Hawfinch': 'https://en.m.wikipedia.org/wiki/Hawfinch',
    'Helmet Vanga': 'https://en.m.wikipedia.org/wiki/Helmet_vanga',
    'Hepatic Tanager': 'https://en.m.wikipedia.org/wiki/Hepatic_tanager',
    'Himalayan Bluetail': 'https://en.m.wikipedia.org/wiki/Himalayan_bluetail',
    'Himalayan Monal': 'https://en.m.wikipedia.org/wiki/Himalayan_monal',
    'Hoatzin': 'https://en.m.wikipedia.org/wiki/Hoatzin',
    'Hooded Merganser': 'https://en.m.wikipedia.org/wiki/Hooded_merganser',
    'Hoopoes': 'https://en.m.wikipedia.org/wiki/Hoopoe',
    'Horned Guan': 'https://en.m.wikipedia.org/wiki/Horned_guan',
    'Horned Lark': 'https://en.m.wikipedia.org/wiki/Horned_lark',
    'Horned Sungem': 'https://en.m.wikipedia.org/wiki/Horned_sungem',
    'House Finch': 'https://en.m.wikipedia.org/wiki/House_finch',
    'House Sparrow': 'https://en.m.wikipedia.org/wiki/House_sparrow',
    'Hyacinth Macaw': 'https://en.m.wikipedia.org/wiki/Hyacinth_macaw',
    'Iberian Magpie': 'https://en.m.wikipedia.org/wiki/Iberian_magpie',
    'Ibisbill': 'https://en.m.wikipedia.org/wiki/Ibisbill',
    'Imperial Shaq': 'https://en.m.wikipedia.org/wiki/Imperial_shag',
    'Inca Tern': 'https://en.m.wikipedia.org/wiki/Inca_tern',
    'Indian Bustard': 'https://en.m.wikipedia.org/wiki/Great_Indian_bustard',
    'Indian Pitta': 'https://en.m.wikipedia.org/wiki/Indian_pitta',
    'Indian Roller': 'https://en.m.wikipedia.org/wiki/Indian_roller',
    'Indian Vulture': 'https://en.m.wikipedia.org/wiki/Indian_vulture',
    'Indigo Bunting': 'https://en.m.wikipedia.org/wiki/Indigo_bunting',
    'Indigo Flycatcher': 'https://en.m.wikipedia.org/wiki/Indigo_flycatcher',
    'Inland Dotterel': 'https://en.m.wikipedia.org/wiki/Inland_dotterel',
    'Ivory Billed Aracari': 'https://en.m.wikipedia.org/wiki/Ivory-billed_aracari',
    'Ivory Gull': 'https://en.m.wikipedia.org/wiki/Ivory_gull',
    'Iwi': 'https://en.m.wikipedia.org/wiki/%CA%BBI%CA%BBiwi',
    'Jabiru': 'https://en.m.wikipedia.org/wiki/Jabiru',
    'Jack Snipe': 'https://en.m.wikipedia.org/wiki/Jack_snipe',
    'Jandaya Parakeet': 'https://en.m.wikipedia.org/wiki/Jandaya_parakeet',
    'Japanese Robin': 'https://en.m.wikipedia.org/wiki/Japanese_robin',
    'Java Sparrow': 'https://en.m.wikipedia.org/wiki/Java_sparrow',
    'Jocotoco Antpitta': 'https://en.m.wikipedia.org/wiki/Jocotoco_antpitta',
    'Kagu': 'https://en.m.wikipedia.org/wiki/Kagu',
    'Kakapo': 'https://en.m.wikipedia.org/wiki/K%C4%81k%C4%81p%C5%8D',
    'Killdear': 'https://en.m.wikipedia.org/wiki/Killdeer',
    'King Eider': 'https://en.m.wikipedia.org/wiki/King_eider',
    'King Vulture': 'https://en.m.wikipedia.org/wiki/King_vulture',
    'Kiwi': 'https://en.m.wikipedia.org/wiki/Kiwi_(bird)',
    'Kookaburra': 'https://en.m.wikipedia.org/wiki/Kookaburra',
    'Lark Bunting': 'https://en.m.wikipedia.org/wiki/Lark_bunting',
    'Lazuli Bunting': 'https://en.m.wikipedia.org/wiki/Lazuli_bunting',
    'Lesser Adjutant': 'https://en.m.wikipedia.org/wiki/Lesser_adjutant',
    'Lilac Roller': 'https://en.m.wikipedia.org/wiki/Lilac-breasted_roller',
    'Little Auk': 'https://en.m.wikipedia.org/wiki/Little_auk',
    'Loggerhead Shrike': 'https://en.m.wikipedia.org/wiki/Loggerhead_shrike',
    'Long-Eared Owl': 'https://en.m.wikipedia.org/wiki/Long-eared_owl',
    'Magpie Goose': 'https://en.m.wikipedia.org/wiki/Magpie_goose',
    'Malabar Hornbill': 'https://en.m.wikipedia.org/wiki/Malabar_grey_hornbill',
    'Malachite Kingfisher': 'https://en.m.wikipedia.org/wiki/Malachite_kingfisher',
    'Malagasy White Eye': 'https://en.m.wikipedia.org/wiki/Malagasy_white-eye',
    'Maleo': 'https://en.m.wikipedia.org/wiki/Maleo',
    'Mallard Duck': 'https://en.m.wikipedia.org/wiki/Mallard',
    'Mandrin Duck': 'https://en.m.wikipedia.org/wiki/Mandarin_duck',
    'Mangrove Cuckoo': 'https://en.m.wikipedia.org/wiki/Mangrove_cuckoo',
    'Marabou Stork': 'https://en.m.wikipedia.org/wiki/Marabou_stork',
    'Masked Booby': 'https://en.m.wikipedia.org/wiki/Masked_booby',
    'Masked Lapwing': 'https://en.m.wikipedia.org/wiki/Masked_lapwing',
    'Mckays Bunting': 'https://en.m.wikipedia.org/wiki/McKay%27s_bunting',
    'Mikado  Pheasant': 'https://en.m.wikipedia.org/wiki/Mikado_pheasant',
    'Mourning Dove': 'https://en.m.wikipedia.org/wiki/Mourning_dove',
    'Myna': 'https://en.m.wikipedia.org/wiki/Myna',
    'Nicobar Pigeon': 'https://en.m.wikipedia.org/wiki/Nicobar_pigeon',
    'Noisy Friarbird': 'https://en.m.wikipedia.org/wiki/Noisy_friarbird',
    'Northern Beardless Tyrannulet': 'https://en.m.wikipedia.org/wiki/Northern_beardless_tyrannulet',
    'Northern Cardinal': 'https://en.m.wikipedia.org/wiki/Northern_cardinal',
    'Northern Flicker': 'https://en.m.wikipedia.org/wiki/Northern_flicker',
    'Northern Fulmar': 'https://en.m.wikipedia.org/wiki/Northern_fulmar',
    'Northern Gannet': 'https://en.m.wikipedia.org/wiki/Northern_gannet',
    'Northern Goshawk': 'https://en.m.wikipedia.org/wiki/Northern_goshawk',
    'Northern Jacana': 'https://en.m.wikipedia.org/wiki/Northern_jacana',
    'Northern Mockingbird': 'https://en.m.wikipedia.org/wiki/Northern_mockingbird',
    'Northern Parula': 'https://en.m.wikipedia.org/wiki/Northern_parula',
    'Northern Red Bishop': 'https://en.m.wikipedia.org/wiki/Northern_red_bishop',
    'Northern Shoveler': 'https://en.m.wikipedia.org/wiki/Northern_shoveler',
    'Ocellated Turkey': 'https://en.m.wikipedia.org/wiki/Ocellated_turkey',
    'Okinawa Rail': 'https://en.m.wikipedia.org/wiki/Okinawa_rail',
    'Orange Brested Bunting': 'https://en.m.wikipedia.org/wiki/Orange-breasted_bunting',
    'Oriental Bay Owl': 'https://en.m.wikipedia.org/wiki/Oriental_bay_owl',
    'Osprey': 'https://en.m.wikipedia.org/wiki/Osprey',
    'Ostrich': 'https://en.m.wikipedia.org/wiki/Ostrich',
    'Ovenbird': 'https://en.m.wikipedia.org/wiki/Ovenbird',
    'Oyster Catcher': 'https://en.m.wikipedia.org/wiki/Oystercatcher',
    'Painted Bunting': 'https://en.m.wikipedia.org/wiki/Painted_bunting',
    'Palila': 'https://en.m.wikipedia.org/wiki/Palila',
    'Paradise Tanager': 'https://en.m.wikipedia.org/wiki/Paradise_tanager',
    'Parakett  Akulet': 'https://en.m.wikipedia.org/wiki/Parakeet_auklet',
    'Parus Major': 'https://en.m.wikipedia.org/wiki/Great_tit',
    'Patagonian Sierra Finch': 'https://en.m.wikipedia.org/wiki/Patagonian_sierra_finch',
    'Peacock': 'https://en.m.wikipedia.org/wiki/Peafowl',
    'Peregrine Falcon': 'https://en.m.wikipedia.org/wiki/Peregrine_falcon',
    'Philippine Eagle': 'https://en.m.wikipedia.org/wiki/Philippine_eagle',
    'Pink Robin': 'https://en.m.wikipedia.org/wiki/Pink_robin',
    'Pomarine Jaeger': 'https://en.m.wikipedia.org/wiki/Pomarine_jaeger',
    'Puffin': 'https://en.m.wikipedia.org/wiki/Puffin',
    'Purple Finch': 'https://en.m.wikipedia.org/wiki/Purple_finch',
    'Purple Gallinule': 'https://en.m.wikipedia.org/wiki/American_purple_gallinule',
    'Purple Martin': 'https://en.m.wikipedia.org/wiki/Purple_martin',
    'Purple Swamphen': 'https://en.m.wikipedia.org/wiki/Australasian_swamphen',
    'Pygmy Kingfisher': 'https://en.m.wikipedia.org/wiki/African_pygmy_kingfisher',
    'Quetzal': 'https://en.m.wikipedia.org/wiki/Quetzal',
    'Rainbow Lorikeet': 'https://en.m.wikipedia.org/wiki/Rainbow_lorikeet',
    'Razorbill': 'https://en.m.wikipedia.org/wiki/Razorbill',
    'Red Bearded Bee Eater': 'https://en.m.wikipedia.org/wiki/Red-bearded_bee-eater',
    'Red Bellied Pitta': 'https://en.m.wikipedia.org/wiki/Red-bellied_pitta',
    'Red Browed Finch': 'https://en.m.wikipedia.org/wiki/Red-browed_finch',
    'Red Faced Cormorant': 'https://en.m.wikipedia.org/wiki/Red-faced_cormorant',
    'Red Faced Warbler': 'https://en.m.wikipedia.org/wiki/Red-faced_warbler',
    'Red Fody': 'https://en.m.wikipedia.org/wiki/Red_fody',
    'Red Headed Duck': 'https://en.m.wikipedia.org/wiki/Redhead_(bird)',
    'Red Headed Woodpecker': 'https://en.m.wikipedia.org/wiki/Red-headed_woodpecker',
    'Red Honey Creeper': 'https://en.m.wikipedia.org/wiki/Red-legged_honeycreeper',
    'Red Naped Trogon': 'https://en.m.wikipedia.org/wiki/Red-naped_trogon',
    'Red Tailed Hawk': 'https://en.m.wikipedia.org/wiki/Red-tailed_hawk',
    'Red Tailed Thrush': 'https://en.m.wikipedia.org/wiki/Red-tailed_laughingthrush',
    'Red Winged Blackbird': 'https://en.m.wikipedia.org/wiki/Red-winged_blackbird',
    'Red Wiskered Bulbul': 'https://en.m.wikipedia.org/wiki/Red-whiskered_bulbul',
    'Regent Bowerbird': 'https://en.m.wikipedia.org/wiki/Regent_bowerbird',
    'Ring-Necked Pheasant': 'https://en.m.wikipedia.org/wiki/Common_pheasant',
    'Roadrunner': 'https://en.m.wikipedia.org/wiki/Roadrunner',
    'Robin': 'https://en.m.wikipedia.org/wiki/American_robin',
    'Rock Dove': 'https://en.m.wikipedia.org/wiki/Rock_dove',
    'Rosy Faced Lovebird': 'https://en.m.wikipedia.org/wiki/Rosy-faced_lovebird',
    'Rough Leg Buzzard': 'https://en.m.wikipedia.org/wiki/Rough-legged_buzzard',
    'Royal Flycatcher': 'https://en.m.wikipedia.org/wiki/Royal_flycatcher',
    'Ruby Throated Hummingbird': 'https://en.m.wikipedia.org/wiki/Ruby-throated_hummingbird',
    'Rudy Kingfisher': 'https://en.m.wikipedia.org/wiki/Ruddy_kingfisher',
    'Rufous Kingfisher': 'https://en.m.wikipedia.org/wiki/Rufous-collared_kingfisher',
    'Rufuos Motmot': 'https://en.m.wikipedia.org/wiki/Rufous_motmot',
    'Samatran Thrush': 'https://en.m.wikipedia.org/wiki/Sumatran_laughingthrush',
    'Sand Martin': 'https://en.m.wikipedia.org/wiki/Sand_martin',
    'Sandhill Crane': 'https://en.m.wikipedia.org/wiki/Sandhill_crane',
    'Satyr Tragopan': 'https://en.m.wikipedia.org/wiki/Satyr_tragopan',
    'Scarlet Crowned Fruit Dove': 'https://en.m.wikipedia.org/wiki/Fruit_dove',
    'Scarlet Ibis': 'https://en.m.wikipedia.org/wiki/Scarlet_ibis',
    'Scarlet Macaw': 'https://en.m.wikipedia.org/wiki/Scarlet_macaw',
    'Scarlet Tanager': 'https://en.m.wikipedia.org/wiki/Scarlet_tanager',
    'Shoebill': 'https://en.m.wikipedia.org/wiki/Shoebill',
    'Short Billed Dowitcher': 'https://en.m.wikipedia.org/wiki/Short-billed_dowitcher',
    'Skua': 'https://en.m.wikipedia.org/wiki/Skua',
    'Smiths Longspur': 'https://en.m.wikipedia.org/wiki/Smith%27s_longspur',
    'Snowy Egret': 'https://en.m.wikipedia.org/wiki/Snowy_egret',
    'Snowy Owl': 'https://en.m.wikipedia.org/wiki/Snowy_owl',
    'Snowy Plover': 'https://en.m.wikipedia.org/wiki/Snowy_plover',
    'Sora': 'https://en.m.wikipedia.org/wiki/Sora_(bird)',
    'Spangled Cotinga': 'https://en.m.wikipedia.org/wiki/Spangled_cotinga',
    'Splendid Wren': 'https://en.m.wikipedia.org/wiki/Splendid_fairywren',
    'Spoon Biled Sandpiper': 'https://en.m.wikipedia.org/wiki/Spoon-billed_sandpiper',
    'Spoonbill': 'https://en.m.wikipedia.org/wiki/Spoonbill',
    'Spotted Catbird': 'https://en.m.wikipedia.org/wiki/Spotted_catbird',
    'Sri Lanka Blue Magpie': 'https://en.m.wikipedia.org/wiki/Sri_Lanka_blue_magpie',
    'Steamer Duck': 'https://en.m.wikipedia.org/wiki/Steamer_duck',
    'Stork Billed Kingfisher': 'https://en.m.wikipedia.org/wiki/Stork-billed_kingfisher',
    'Strawberry Finch': 'https://en.m.wikipedia.org/wiki/Red_avadavat',
    'Striped Owl': 'https://en.m.wikipedia.org/wiki/Striped_owl',
    'Stripped Manakin': 'https://en.m.wikipedia.org/wiki/Kinglet_manakin',
    'Stripped Swallow': 'https://en.m.wikipedia.org/wiki/Lesser_striped_swallow',
    'Superb Starling': 'https://en.m.wikipedia.org/wiki/Superb_starling',
    'Swinhoes Pheasant': 'https://en.m.wikipedia.org/wiki/Swinhoe%27s_pheasant',
    'Tailorbird': 'https://en.m.wikipedia.org/wiki/Tailorbird',
    'Taiwan Magpie': 'https://en.m.wikipedia.org/wiki/Taiwan_blue_magpie',
    'Takahe': 'https://en.m.wikipedia.org/wiki/Takah%C4%93',
    'Tasmanian Hen': 'https://en.m.wikipedia.org/wiki/Tasmanian_nativehen',
    'Teal Duck': 'https://en.m.wikipedia.org/wiki/Green-winged_teal',
    'Tit Mouse': 'https://en.m.wikipedia.org/wiki/Tufted_titmouse',
    'Touchan': 'https://en.m.wikipedia.org/wiki/Toucan',
    'Townsends Warbler': 'https://en.m.wikipedia.org/wiki/Townsend%27s_warbler',
    'Tree Swallow': 'https://en.m.wikipedia.org/wiki/Tree_swallow',
    'Tricolored Blackbird': 'https://en.m.wikipedia.org/wiki/Tricolored_blackbird',
    'Tropical Kingbird': 'https://en.m.wikipedia.org/wiki/Tropical_kingbird',
    'Trumpter Swan': 'https://en.m.wikipedia.org/wiki/Trumpeter_swan',
    'Turkey Vulture': 'https://en.m.wikipedia.org/wiki/Turkey_vulture',
    'Turquoise Motmot': 'https://en.m.wikipedia.org/wiki/Turquoise-browed_motmot',
    'Umbrella Bird': 'https://en.m.wikipedia.org/wiki/Umbrellabird',
    'Varied Thrush': 'https://en.m.wikipedia.org/wiki/Varied_thrush',
    'Veery': 'https://en.m.wikipedia.org/wiki/Veery',
    'Venezuelian Troupial': 'https://en.m.wikipedia.org/wiki/Venezuelan_troupial',
    'Vermilion Flycather': 'https://en.m.wikipedia.org/wiki/Vermilion_flycatcher',
    'Victoria Crowned Pigeon': 'https://en.m.wikipedia.org/wiki/Victoria_crowned_pigeon',
    'Violet Green Swallow': 'https://en.m.wikipedia.org/wiki/Violet-green_swallow',
    'Violet Turaco': 'https://en.m.wikipedia.org/wiki/Violet_turaco',
    'Vulturine Guineafowl': 'https://en.m.wikipedia.org/wiki/Vulturine_guineafowl',
    'Wall Creaper': 'https://en.m.wikipedia.org/wiki/Wallcreeper',
    'Wattled Curassow': 'https://en.m.wikipedia.org/wiki/Wattled_curassow',
    'Wattled Lapwing': 'https://en.m.wikipedia.org/wiki/African_wattled_lapwing',
    'Whimbrel': 'https://en.m.wikipedia.org/wiki/Eurasian_whimbrel',
    'White Browed Crake': 'https://en.m.wikipedia.org/wiki/White-browed_crake',
    'White Cheeked Turaco': 'https://en.m.wikipedia.org/wiki/White-cheeked_turaco',
    'White Crested Hornbill': 'https://en.m.wikipedia.org/wiki/White-crested_hornbill',
    'White Necked Raven': 'https://en.m.wikipedia.org/wiki/White-necked_raven',
    'White Tailed Tropic': 'https://en.m.wikipedia.org/wiki/White-tailed_tropicbird',
    'White Throated Bee Eater': 'https://en.m.wikipedia.org/wiki/White-throated_bee-eater',
    'Wild Turkey': 'https://en.m.wikipedia.org/wiki/Wild_turkey',
    'Wilsons Bird Of Paradise': 'https://en.m.wikipedia.org/wiki/Wilson%27s_bird-of-paradise',
    'Wood Duck': 'https://en.m.wikipedia.org/wiki/Wood_duck',
    'Yellow Bellied Flowerpecker': 'https://en.m.wikipedia.org/wiki/Yellow-bellied_flowerpecker',
    'Yellow Cacique': 'https://en.m.wikipedia.org/wiki/Yellow-rumped_cacique',
    'Yellow Headed Blackbird': 'https://en.m.wikipedia.org/wiki/Yellow-headed_blackbird',

  };

}